### ISSUE TITLE
Modify ui state based on non-redux-ui actions

### ISSUE THREAD

**Issue by codyhatch** [tonyhb/redux-ui#4]
At the moment I'm using my own UI-State reducer which, among other things, listens for the `UPDATE_PATH` action from `redux-simple-router`; I do this so I can set intitial UI state based on query strings.

Eg, if someone loads `http://<myapp>/search?extra_filters=true`, then I want to be able to set `ui.extra_filters` to true.  How can I achieve this with `redux-ui`?

`redux-form` has a solution in the form of it's plugin API:  http://erikras.github.io/redux-form/#/api/reducer/plugin?_k=xqjy5h

Perhaps something similar could be implemented here?

**Comment by tonyhb** [comment]
Good question!  Setting UI state from router is probably going to be common.  Can imagine setting UI state from user preferences will also be required (added as #5).

**Possible solution**:

The initial solution I'm thinking is that the `state` option can accept a function with signature `(props) => ({ vars })`, eg:

`(state) => ({ var1: 'something', extra_filters: state.router.extra_filters })`

If we see that the `state` option has a function pass in all state from Redux' store to calculate initial values.

---

A question for you to get this right and consider your implementation:
1. When the UI value is toggled does the router update?
2. If so, we're going to need to sync both the router and UI reducer at the same time which necessitates something like redux-form's plugins

A plugin API is an interesting approach and will take a little bit of planning to get right.  I'd like to consider this when we've had a couple more questions and use cases so we know we're doing the right thing here.

redux-form's implementation of listening for actions is really interesting.

**Comment by codyhatch** [comment]
> When the UI value is toggled does the router update?

No, what I'm doing is a complicated search form with a lot of fields, some of which are hidden by default behind an "advanced search" toggle, and a search button.  On page load the fields are pre-populated from the URL by redux-form, and when the search button is hit the state is serialised to the URL, but nothing else changes the URL.

So if the page loads with an url like `http://<app>/search?name=foo` then extra_filters should stay false, because the name field isn't one of my advanced fields.  But if the url is something like `http://<app>/search?platform=ios,android&show_unconfirmed=true`, then I need to set extra_filters to true, because show_unconfirmed as an advanced field.  On the other hand if the user clicks the "advanced search" button, I _just_ need to update extra_filters to true; the URL doesn't update until the user runs a new search (and even then extra_filters doesn't get serialized to the URL).

I think your proposed solution would work, although it feels a bit odd to me; right now all the logic for turning a `redux-simple-router` event into updated state lives in a reducer, which I think is idiomatic for redux.  With this change, a lot of logic would be moved into the container, which I suppose is okay?

**Comment by tonyhb** [comment]
+1 agreed that it's a bit odd, and as we're receiving the action anyway it'd be good to be able to extend the reducer that `redux-ui` uses.

We'd actually need this to solve one of our own problems:  if you submit a form and a resource is created we want to hide the form.  That'd be done via the specific create action.

Will work on an implementation after finishing up a few more tests today

**Comment by tonyhb** [comment]
Added an initial implementation of a [reducer enhancer here (similar to redux-form's plugins, except global instead of per form):](https://github.com/tonyhb/redux-ui/pull/6)  https://github.com/tonyhb/redux-ui/pull/6

Note that we can't do this per-component because each component's UI state is stored _nested_ within its parents state.  This is to facilitate the whole 'block-level scoping' approach to UI;  if we exit out of the outer scope (unmount a parent) all child state should be blown away.

This means that **we need to know the key/path for each component's UI state we want to modify**.  This isn't particularly great.

Solutions:
1. Don't store UI state in a tree
2. Add the ability for each component to also listen to actions within the `@ui` declaration
3. Record the paths for each component within the UI reducer and use the same style of plugins as redux-form:

```
enhancedReducer({
  keyName: (state, action) => {
  }
});
```

**Comment by tonyhb** [comment]
Had a bit of a think about this and I'm leaning towards actually specifying the actions that you'd like to manipulate UI state within the components themselves:

``` js
// Explicitly defining the actions to listen to as an object
@ui({
  key: 'someKey',
  state: {
    extraFilters: false
  },
  reducer: (state, action) => {
      // state represents *only* the UI state for this component's scope - not any children
      switch(action.type) {
      case '@@reduxReactRouter/routerDidChange':
        if (action.payload.location.query.extra_filters) {
          return state.set('extraFilters', true);
        }
      }
      return state;
    }
  }
});
```

Primarily interested in this approach because it logically groups all UI state together.  It's technically more verbose and I'm making peace with it blending a reducer in with a component;  you could always define these router functions elsewhere and import them.

The other alternative I'm exploring is the enhancedReducer pattern above:

``` js
const uiReducer = enhancedUIReducer({
  'someUIKey': (state, action) => {
    // state represents *only* the UI state for this component's scope - not any children
    switch(action.type) {
    case '@@reduxReactRouter/routerDidChange':
      if (action.payload.location.query.extra_filters) {
        return state.set('extraFilters', true);
      }
    }
    return state;
  }
});

combineReducers({ ...yourReducers, ui: uiReducer });
```

This approach will run the function above for _all_ UI components with the key of `someUIKey`. This means that auto-generated keys can't have custom reducers, which is technically a small negative but removes the ability to use this in lists.

I like this as each reducer is techincally separate and defined alongside normal reducers.  Still, it's kind of clunky to have the UI definitions separate from the reducers.

**Comment by tonyhb** [comment]
@codyhatch This should do the trick for you, based on the above post:  https://github.com/tonyhb/redux-ui/pull/7

Going to close this and release a new version on NPM in a sec.

**Comment by tonyhb** [comment]
v0.0.7 has been published with this functionality and unit tests.  Marking as closed unless we need anything else :+1:
